---
name: build-workstation
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-workstation.yml'
      - '.github/workflows/build.yml'
      - 'build/workstation/*'
      - 'build/base/*'
      - '!**/*.md'
  schedule:
    - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-workstation.yml'
      - '.github/workflows/build.yml'
      - 'build/workstation/*'
      - 'build/base/*'
      - '!**/*.md'
  workflow_dispatch:

jobs:
  build_workstation:
    name: Build and push workstation image
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    strategy:
      max-parallel: 4
      matrix:
        upstream_suffix:
          - ""
          - "nvidia"
    uses: ./.github/workflows/build.yml
    with:
      permutation: "workstation"
      image_suffix: ${{ matrix.upstream_suffix }}

  build_workstation_nofun:
    name: Build and push workstation-nofun image
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
    strategy:
      max-parallel: 4
      matrix:
        upstream_suffix:
          - ""
          - "nvidia"
    uses: ./.github/workflows/build.yml
    with:
      permutation: "workstation-nofun"
      image_suffix: ${{ matrix.upstream_suffix }}
